#!/bin/bash
LAST_COMMIT_HASH=$(git rev-parse HEAD | cat)
PREVIOUS_MERGE_HASH=$(git rev-list --merges --first-parent --skip=1 --max-count=1 HEAD | cat)
PREVIOUS_MERGE_DATE=$(git show --no-patch --no-notes --pretty='%cd' --date=short $PREVIOUS_MERGE_HASH | cat)
NEXT=$(date +%F)
echo "#"$CI_PROJECT_NAME
echo "##Changelog" $CI_COMMIT_REF_NAME
echo "> Commits since the" $PREVIOUS_MERGE_DATE
git log --no-merges --format="%cd" --date=short $PREVIOUS_MERGE_HASH..$LAST_COMMIT_HASH | sort -u -r | while read DATE ; do
    echo
    echo "###"$DATE
    GIT_PAGER=cat git log --no-merges --format=" * %s" --since="$DATE 00:00:00" --until="$DATE 24:00:00" $PREVIOUS_MERGE_HASH..$LAST_COMMIT_HASH
done